"""YAML read/write for project.yaml state management."""

import asyncio
import errno
import fcntl
import hashlib
import logging
import os
import re
import stat
import threading
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Callable, Hashable, Optional

import yaml

# libyaml (C) loader/dumper are ~14-16x faster than the pure-Python ones on a
# large project.yaml (e.g. ~1MB/350-PR: load 1480ms -> 93ms, dump 1130ms ->
# 80ms). The WriteQueue drains run via ``asyncio.to_thread``; pure-Python
# (de)serialization holds the GIL except for the ~5ms switch interval, so it
# contends with the event loop for CPU and throttles TUI repaints while a write
# is in flight. The C path releases the GIL, so background drains are fast and
# don't steal CPU from the UI.
#
# Loader: always prefer C when available — parsing is byte-irrelevant and the C
# loader produces identical objects, so there is no compatibility risk.
#
# Dumper: the C dumper wraps long scalars (e.g. multi-line PR descriptions)
# differently from the pure-Python dumper. Both are valid YAML and parse
# identically, but the bytes differ, which would churn the committed
# project.yaml whenever a save lands on an environment with a different backend.
# So the C dumper is gated by the per-project ``project.libyaml`` flag (default
# OFF): pure-Python output is byte-stable across mixed environments, so it is the
# safe default. Set ``libyaml: true`` to opt into the faster C dumper where every
# writer is known to share the C backend. Defaulting off (rather than on) means a
# dropped/absent flag degrades to stable output instead of silently reformatting
# the whole file the next time a writer with the C backend saves.
try:
    from yaml import CSafeLoader as _CSafeLoader, CSafeDumper as _CSafeDumper
except ImportError:  # pragma: no cover - depends on the PyYAML build
    _CSafeLoader = _CSafeDumper = None


def _yaml_loader():
    return _CSafeLoader or yaml.SafeLoader


def _yaml_dumper(data: dict):
    if _CSafeDumper is not None and (data.get("project") or {}).get("libyaml", False):
        return _CSafeDumper
    return yaml.SafeDumper

_log = logging.getLogger("pm.store")

_YAML_HEADER = (
    "# WARNING: Do not edit this file directly — use 'pm' commands.\n"
    "# Manual changes may be overwritten by concurrent pm processes.\n"
    "# Use 'pm edit' to safely open this file in your editor with locking.\n"
    "#\n"
    "# This file is kept read-only as a safety measure. pm commands\n"
    "# acquire a lock and temporarily make it writable when saving.\n"
)


class ProjectYamlParseError(Exception):
    """Raised when project.yaml cannot be parsed (e.g. mid-edit or merge conflict)."""


class PlanValidationError(Exception):
    """Raised when plan entries have invalid references (e.g. bad parent ID, cycles)."""


VALID_PLAN_STATUSES = {"draft", "active", "done"}


def find_project_root(start: Optional[str] = None) -> Path:
    """Walk up from start (or cwd) to find directory containing project.yaml.

    Looks for pm/project.yaml first (PM dir inside target repo),
    then falls back to project.yaml (standalone PM repo) for backward compat.
    """
    p = Path(start) if start else Path.cwd()
    for d in [p, *p.parents]:
        if (d / "pm" / "project.yaml").exists():
            return d / "pm"
        if (d / "project.yaml").exists():
            return d
    raise FileNotFoundError(
        "No project.yaml found. Either cd into your repo, "
        "use 'pm -C /path/to/pm-dir', or set PM_PROJECT=/path/to/pm-dir"
    )


def is_internal_pm_dir(root: Path) -> bool:
    """Check if the PM dir is inside a target repo (pm/ subdir) vs standalone."""
    return root.name == "pm" and (root.parent / ".git").exists()


# Git conflict-marker line prefixes. A bare ``=======`` (exactly seven equals)
# is also a marker; we match it separately so a legitimate YAML value never
# trips the check.
_CONFLICT_MARKER_PREFIXES = ("<<<<<<< ", "||||||| ", ">>>>>>> ")


def find_conflict_markers(text: str) -> list[tuple[int, str]]:
    """Return ``(1-based line number, line)`` for any git conflict markers.

    Detects the markers left by a failed ``git stash pop`` / merge:
    ``<<<<<<< ``, ``||||||| `` (diff3 base), ``>>>>>>> `` and a bare
    ``=======`` separator.  The separator must be exactly seven equals so a
    normal YAML scalar/key never counts as a false positive.
    """
    hits: list[tuple[int, str]] = []
    for i, line in enumerate(text.splitlines(), 1):
        if line.startswith(_CONFLICT_MARKER_PREFIXES) or line.rstrip() == "=======":
            hits.append((i, line))
    return hits


def load(root: Optional[Path] = None, validate: bool = True) -> dict:
    """Load project.yaml from root directory.

    Args:
        root: Directory containing project.yaml
        validate: If True, validate PR statuses, plan statuses, and parent references
    """
    if root is None:
        root = find_project_root()
    path = root / "project.yaml"
    try:
        with open(path) as f:
            text = f.read()
    except FileNotFoundError:
        # Preserve the historical contract: a missing project.yaml raises
        # FileNotFoundError, which several callers catch to mean "no project"
        # (guide.detect_state, tui.sync, session init).  Only wrap *other*
        # read errors (permission, IsADirectory, …) as a parse error.
        raise
    except OSError as e:
        raise ProjectYamlParseError(f"Could not read {path}: {e}") from e

    # Guard against git conflict markers (e.g. a failed auto-stash pop during
    # a merge).  project.yaml is the lock-protected source of truth, so a raw
    # YAML scanner traceback here would be opaque; report the offending line
    # and remediation instead.
    markers = find_conflict_markers(text)
    if markers:
        lineno, marker = markers[0]
        raise ProjectYamlParseError(
            f"{path} contains git conflict markers from a failed stash/merge: "
            f"line {lineno}: {marker.rstrip()!r}. Resolve the markers (or restore "
            f"the file from git, e.g. 'git checkout -- {path.name}'), then re-run."
        )

    try:
        data = yaml.load(text, Loader=_yaml_loader())
    except yaml.YAMLError as e:
        raise ProjectYamlParseError(f"project.yaml is not valid YAML: {e}") from e

    if data is None:
        data = {}

    if not isinstance(data, dict):
        raise ProjectYamlParseError(
            "project.yaml is not valid YAML: expected a mapping at the top level"
        )

    if validate:
        _validate_pr_statuses(data)
        _validate_plans(data)

    return data


def _validate_pr_statuses(data: dict) -> None:
    """Validate and fix PR statuses in loaded data."""
    from pm_core.pr_utils import VALID_PR_STATES

    for pr in data.get("prs") or []:
        status = pr.get("status")
        if status not in VALID_PR_STATES:
            # Default invalid statuses to "pending"
            pr["status"] = "pending"
        # Backfill created_at / updated_at for PRs that predate these fields.
        # Use the best available timestamp so sorting works immediately.
        if not pr.get("created_at"):
            pr["created_at"] = (pr.get("started_at")
                                or pr.get("reviewed_at")
                                or pr.get("merged_at"))
        if not pr.get("updated_at"):
            pr["updated_at"] = (pr.get("merged_at")
                                or pr.get("reviewed_at")
                                or pr.get("started_at"))


def _validate_plans(data: dict) -> None:
    """Validate plan entries: normalize statuses, check parent references, detect cycles."""
    plans = data.get("plans") or []
    plan_ids = {p["id"] for p in plans}

    for plan in plans:
        # Status normalization (silent fix, same as PRs)
        if plan.get("status") not in VALID_PLAN_STATUSES:
            plan["status"] = "draft"

        # Backfill missing parent field
        if "parent" not in plan:
            plan["parent"] = None

        # Validate parent reference
        parent = plan["parent"]
        if parent is not None and parent not in plan_ids:
            raise PlanValidationError(
                f"Plan {plan['id']} references non-existent parent '{parent}'"
            )

    # Cycle detection: walk parent chains with a visited set
    parent_map = {p["id"]: p.get("parent") for p in plans}
    for plan_id in plan_ids:
        visited = set()
        current = plan_id
        while current is not None:
            if current in visited:
                raise PlanValidationError(
                    f"Cycle detected in plan hierarchy involving '{plan_id}'"
                )
            visited.add(current)
            current = parent_map.get(current)


def save(data: dict, root: Optional[Path] = None) -> None:
    """Write project.yaml to root directory.

    Uses atomic write (write to temp file, then rename) so concurrent
    readers never see a truncated or partially-written file.

    Makes the file writable before writing and read-only afterwards
    so that casual manual edits are blocked with a permission error.
    """
    if root is None:
        root = find_project_root()
    path = root / "project.yaml"
    # Make writable if it exists and is read-only
    if path.exists():
        path.chmod(path.stat().st_mode | stat.S_IWUSR)
    # Atomic write: write to temp file, then rename
    tmp = path.with_suffix(".yaml.tmp")
    with open(tmp, "w") as f:
        f.write(_YAML_HEADER)
        yaml.dump(
            data, f, Dumper=_yaml_dumper(data),
            default_flow_style=False, sort_keys=False, allow_unicode=True,
        )
        f.flush()
        os.fsync(f.fileno())
    tmp.rename(path)
    # Set read-only (owner read, group/other read)
    path.chmod(stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)


def make_plan_entry(
    plan_id: str,
    name: str,
    file: str,
    *,
    status: str = "draft",
    parent: Optional[str] = None,
) -> dict:
    """Create a standard plan entry dict with all required keys."""
    return {
        "id": plan_id,
        "name": name,
        "file": file,
        "status": status,
        "parent": parent,
    }


# ---------------------------------------------------------------------------
# Advisory file locking for read-modify-write operations
# ---------------------------------------------------------------------------

LOCK_TIMEOUT_SECONDS = 2.0


class StoreLockTimeout(Exception):
    """Raised when the project.yaml lock cannot be acquired within the timeout."""


@contextmanager
def _lock(root: Path, timeout: float = LOCK_TIMEOUT_SECONDS):
    """Acquire an exclusive advisory lock on project.yaml.lock.

    Yields the open lock file descriptor. The lock is released when the
    context manager exits (even on exception).
    """
    lock_path = root / "project.yaml.lock"
    deadline = time.monotonic() + timeout
    fd = open(lock_path, "a")
    try:
        while True:
            try:
                fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
                break
            except OSError as e:
                if e.errno not in (errno.EACCES, errno.EAGAIN):
                    raise
                if time.monotonic() >= deadline:
                    fd.close()
                    raise StoreLockTimeout(
                        f"Could not acquire lock on {lock_path} within "
                        f"{timeout}s — another pm process may be writing "
                        f"project.yaml. If no other process is running, "
                        f"delete {lock_path} and retry."
                    ) from None
                time.sleep(0.05)
        yield fd
    finally:
        if not fd.closed:
            try:
                fcntl.flock(fd, fcntl.LOCK_UN)
            except OSError:
                pass
            fd.close()


def locked_update(
    root: Path,
    fn: Callable[[dict], None],
    validate: bool = True,
    timeout: float = LOCK_TIMEOUT_SECONDS,
) -> dict:
    """Atomic read-modify-write for project.yaml.

    Acquires an exclusive advisory lock, loads fresh state from disk,
    calls ``fn(data)`` to apply mutations in-place, saves, and releases
    the lock.  Returns the updated data dict.

    The lock must **never** be held across network calls.  If your
    operation needs to call GitHub/git first, do that *before* calling
    ``locked_update`` and pass the results into ``fn`` via a closure.

    Raises ``StoreLockTimeout`` if the lock cannot be acquired within
    *timeout* seconds (default 2).
    """
    with _lock(root, timeout):
        data = load(root, validate=validate)
        fn(data)
        save(data, root)
    return data


# ---------------------------------------------------------------------------
# Structured 3-way merge for reconciling concurrent project.yaml edits
# ---------------------------------------------------------------------------

_MISSING = object()

# Lists in project.yaml that are collections of dicts keyed by ``id`` and so
# should be merged element-wise (by id) rather than as opaque scalars.
_ID_KEYED_LISTS = ("prs", "plans")


def _is_id_list(value) -> bool:
    return (
        isinstance(value, list)
        and value
        and all(isinstance(x, dict) and "id" in x for x in value)
    )


def _three_way_value(base, ours, theirs):
    """3-way merge a single value (recursing into dicts / id-keyed lists)."""
    if ours == theirs:
        return ours
    if base == ours:
        # Only theirs changed → take theirs.
        return theirs
    if base == theirs:
        # Only ours changed → take ours.
        return ours
    # Both sides diverged from base.
    if isinstance(ours, dict) and isinstance(theirs, dict):
        return _three_way_dict(
            base if isinstance(base, dict) else {}, ours, theirs
        )
    if _is_id_list(ours) and _is_id_list(theirs):
        return _three_way_id_list(
            base if isinstance(base, list) else [], ours, theirs
        )
    # Unmergeable conflicting leaves: prefer ours (the committed / post-merge
    # authority).  The dropped side is almost always a transient bookkeeping
    # field (e.g. updated_at) that the next locked_update re-asserts.
    return ours


def _three_way_dict(base: dict, ours: dict, theirs: dict) -> dict:
    result: dict = {}
    for key in list(ours.keys()) + [k for k in theirs if k not in ours]:
        b = base.get(key, _MISSING)
        o = ours.get(key, _MISSING)
        t = theirs.get(key, _MISSING)
        if o is _MISSING:
            # ours deleted; honor theirs only if theirs == base (untouched).
            if t is not _MISSING and t != b:
                result[key] = t
            continue
        if t is _MISSING:
            # theirs deleted; drop only if ours == base (ours untouched).
            if o != b:
                result[key] = o
            continue
        result[key] = _three_way_value(
            None if b is _MISSING else b, o, t
        )
    return result


def _three_way_id_list(base: list, ours: list, theirs: list) -> list:
    """Merge two lists of id-keyed dicts against their common ancestor."""
    def by_id(items):
        return {x["id"]: x for x in items if isinstance(x, dict) and "id" in x}

    b, o, t = by_id(base), by_id(ours), by_id(theirs)
    result: list = []
    seen: set = set()
    # Preserve ours' order, then append theirs-only entries.
    for item in ours:
        if not (isinstance(item, dict) and "id" in item):
            continue
        pid = item["id"]
        seen.add(pid)
        if pid in t:
            result.append(_three_way_dict(b.get(pid, {}), item, t[pid]))
        elif pid in b and pid not in t:
            # theirs deleted it; keep only if ours changed it from base.
            if item != b[pid]:
                result.append(item)
        else:
            result.append(item)
    for item in theirs:
        if not (isinstance(item, dict) and "id" in item):
            continue
        pid = item["id"]
        if pid in seen:
            continue
        # theirs-only: a new entry unless ours deleted a base entry untouched.
        if pid in b and item == b[pid]:
            continue
        result.append(item)
    return result


def three_way_merge(base: dict, ours: dict, theirs: dict) -> dict:
    """Reconcile two divergent project.yaml dicts against a common ancestor.

    Used to re-apply local (uncommitted) bookkeeping edits on top of a freshly
    merged project.yaml without a text-level conflict.  ``ours`` is the
    post-merge / current on-disk state (the authority on tie-breaks);
    ``theirs`` is the stashed-aside local edit; ``base`` is the committed
    ancestor both derive from.  ``prs`` and ``plans`` are merged element-wise
    by ``id``.
    """
    base = base if isinstance(base, dict) else {}
    ours = ours if isinstance(ours, dict) else {}
    theirs = theirs if isinstance(theirs, dict) else {}
    return _three_way_dict(base, ours, theirs)


class WriteQueue:
    """Coalescing write queue for project.yaml mutations.

    The TUI keeps its working state in memory (``app._data``) and must not
    block the asyncio event loop on a file lock + full-yaml parse + rewrite
    for every mutation (e.g. the per-keypress ``active_pr`` persist).  This
    queue decouples in-memory updates from disk:

    * ``enqueue(key, fn)`` records a pending mutation closure tagged by
      *key* and returns immediately.  Re-enqueuing the same *key* replaces
      the pending closure (coalescing), so a burst of rapid updates to the
      same field collapses to a single disk write of the final value.
    * A background worker (``run``) drains the queue after a short
      *debounce* window and applies all pending closures in one
      :func:`locked_update`, which re-reads fresh on-disk state under the
      lock first — so concurrent external edits from other pm processes are
      respected, not clobbered.
    * The blocking ``locked_update`` runs on a thread (``to_thread``) so the
      event loop stays responsive even while a write is in flight.
    * ``flush_sync`` drains synchronously for shutdown paths (``on_unmount``,
      ``restart``) where the worker may not get another chance to run.

    The worker writes to disk only; it never mutates ``app._data``.  In-memory
    state is the source of truth for the running TUI and is re-synced from disk
    by the existing background-sync / reload paths.
    """

    def __init__(
        self,
        root: Path,
        *,
        validate: bool = True,
        timeout: float = LOCK_TIMEOUT_SECONDS,
        debounce: float = 0.1,
    ) -> None:
        self._root = root
        self._validate = validate
        self._timeout = timeout
        self._debounce = debounce
        self._pending: "dict[Hashable, Callable[[dict], None]]" = {}
        self._lock = threading.Lock()
        self._event = asyncio.Event()
        self._stopped = False

    def enqueue(self, key: Hashable, fn: Callable[[dict], None]) -> None:
        """Record a pending mutation, replacing any prior op with the same key."""
        with self._lock:
            self._pending[key] = fn
        # Wake the worker.  set() is safe to call from the event-loop thread;
        # enqueue is only ever called there (TUI key handling).
        self._event.set()

    def _take_pending(self) -> "dict[Hashable, Callable[[dict], None]]":
        """Atomically swap out and return the pending ops."""
        with self._lock:
            ops = self._pending
            self._pending = {}
        return ops

    def _drain_once(self) -> None:
        """Apply all currently-pending ops in one locked read-modify-write.

        Swaps the pending map out under the lock first, so a concurrent
        drainer (e.g. the worker thread vs. a ``flush_sync`` on shutdown)
        only ever applies a given op once.  No-op when nothing is pending.
        """
        ops = self._take_pending()
        if not ops:
            return

        def apply(data: dict) -> None:
            for op in ops.values():
                op(data)

        locked_update(self._root, apply, validate=self._validate,
                      timeout=self._timeout)

    async def run(self) -> None:
        """Worker coroutine: debounce bursts, then drain off the event loop."""
        while not self._stopped:
            await self._event.wait()
            # Resetting debounce: keep waiting while new enqueues keep
            # arriving within the debounce window, so a held key collapses
            # to a single write of the final value once input goes quiet.
            while not self._stopped:
                self._event.clear()
                try:
                    await asyncio.wait_for(self._event.wait(), timeout=self._debounce)
                except asyncio.TimeoutError:
                    break
            try:
                await asyncio.to_thread(self._drain_once)
            except (StoreLockTimeout, ProjectYamlParseError) as e:
                _log.warning("WriteQueue drain failed: %s", e)
            except Exception:
                _log.exception("WriteQueue drain raised")

    def stop(self) -> None:
        """Signal the worker to exit after its current cycle."""
        self._stopped = True
        self._event.set()

    def flush_sync(self) -> None:
        """Drain any pending ops synchronously (for shutdown / restart paths)."""
        try:
            self._drain_once()
        except (StoreLockTimeout, ProjectYamlParseError) as e:
            _log.warning("WriteQueue flush failed: %s", e)
        except Exception:
            _log.exception("WriteQueue flush raised")


def locked_edit(root: Path, timeout: float = 30.0) -> dict:
    """Open project.yaml in $EDITOR under the advisory lock.

    Holds the lock for the entire editing session so no concurrent
    pm process can overwrite the user's changes.  On editor exit,
    re-reads and validates the file, writes it back with the standard
    header and read-only permissions, and releases the lock.

    Returns the final data dict.

    Raises ``StoreLockTimeout`` if the lock cannot be acquired.
    """
    import shlex
    import subprocess

    editor = os.environ.get("EDITOR", "vi")
    path = root / "project.yaml"

    with _lock(root, timeout):
        # Make writable for the editor
        if path.exists():
            path.chmod(path.stat().st_mode | stat.S_IWUSR)
        try:
            subprocess.run([*shlex.split(editor), str(path)], check=True)
        except (subprocess.CalledProcessError, FileNotFoundError) as e:
            # Restore read-only even on editor failure
            if path.exists():
                path.chmod(stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)
            raise RuntimeError(f"Editor failed: {e}") from e

        # Re-read, validate, and re-save with header + permissions
        data = load(root, validate=True)
        save(data, root)
    return data


def next_plan_id(data: dict) -> str:
    """Generate next plan-NNN id."""
    plans = data.get("plans") or []
    if not plans:
        return "plan-001"
    nums = []
    for p in plans:
        m = re.match(r"plan-(\d+)", p["id"])
        if m:
            nums.append(int(m.group(1)))
    return f"plan-{max(nums) + 1:03d}"


def next_pr_id(data: dict) -> str:
    """Generate next pr-NNN id."""
    prs = data.get("prs") or []
    if not prs:
        return "pr-001"
    nums = []
    for p in prs:
        m = re.match(r"pr-(\d+)", p["id"])
        if m:
            nums.append(int(m.group(1)))
    return f"pr-{max(nums) + 1:03d}"


def generate_plan_id(name: str, existing_ids: set[str] | None = None, description: str = "") -> str:
    """Generate a plan ID from a hash of the plan name and description.

    Uses sha256(name + description) truncated to 7 hex chars, producing IDs like
    'plan-a3f2b1c'. If the ID collides with an existing one, extends
    the hash until unique.
    """
    digest = hashlib.sha256((name + description).encode()).hexdigest()
    min_len = 7
    for length in range(min_len, len(digest) + 1):
        plan_id = f"plan-{digest[:length]}"
        if existing_ids is None or plan_id not in existing_ids:
            return plan_id
    for i in range(2, 1000):
        plan_id = f"plan-{digest[:min_len]}-{i}"
        if existing_ids is None or plan_id not in existing_ids:
            return plan_id
    raise RuntimeError("Could not generate unique plan ID")


def generate_pr_id(title: str, desc: str = "", existing_ids: set[str] | None = None) -> str:
    """Generate a PR ID from a hash of title and description.

    Uses sha256(title + newline + desc) truncated to 7 hex chars,
    producing IDs like 'pr-a3f2b1c'. If the ID collides with an
    existing one, extends the hash until unique.

    Backwards compatible: old pr-001 style IDs continue to work
    everywhere since IDs are just opaque strings.
    """
    digest = hashlib.sha256(f"{title}\n{desc}".encode()).hexdigest()
    min_len = 7
    for length in range(min_len, len(digest) + 1):
        pr_id = f"pr-{digest[:length]}"
        if existing_ids is None or pr_id not in existing_ids:
            return pr_id
    # Extremely unlikely: full hash collision. Append counter.
    for i in range(2, 1000):
        pr_id = f"pr-{digest[:min_len]}-{i}"
        if existing_ids is None or pr_id not in existing_ids:
            return pr_id
    raise RuntimeError("Could not generate unique PR ID")


def generate_note_id(pr_id: str, text: str, existing_ids: set[str] | None = None) -> str:
    """Generate a note ID from a hash of the PR ID and note text.

    Uses sha256(pr_id + newline + text) truncated to 7 hex chars,
    producing IDs like 'note-a3f2b1c'. If the ID collides with an
    existing one, extends the hash until unique.
    """
    digest = hashlib.sha256(f"{pr_id}\n{text}".encode()).hexdigest()
    min_len = 7
    for length in range(min_len, len(digest) + 1):
        note_id = f"note-{digest[:length]}"
        if existing_ids is None or note_id not in existing_ids:
            return note_id
    for i in range(2, 1000):
        note_id = f"note-{digest[:min_len]}-{i}"
        if existing_ids is None or note_id not in existing_ids:
            return note_id
    raise RuntimeError("Could not generate unique note ID")


def get_pr(data: dict, pr_id: str) -> Optional[dict]:
    """Get a PR entry by id."""
    for pr in data.get("prs") or []:
        if pr["id"] == pr_id:
            return pr
    return None


def get_plan(data: dict, plan_id: str) -> Optional[dict]:
    """Get a plan entry by id."""
    for plan in data.get("plans") or []:
        if plan["id"] == plan_id:
            return plan
    return None


def slugify(text: str) -> str:
    """Convert text to branch-name-safe slug."""
    s = text.lower().strip()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")[:50]


def init_project(root: Path, name: str, repo: str, base_branch: str = "master",
                  backend: str = "vanilla") -> dict:
    """Create initial project.yaml in a new PM repo.

    The PM repo is separate from the target codebase repo.
    It contains only project.yaml and plans/ — the source of truth
    for project state, owned by PMs. Contributors interact via
    issues or in person, never touching this repo directly.
    """
    data = {
        "project": {
            "name": name,
            "repo": repo,
            "base_branch": base_branch,
            "backend": backend,
        },
        "plans": [],
        "prs": [],
    }
    root.mkdir(parents=True, exist_ok=True)
    (root / "plans").mkdir(exist_ok=True)
    save(data, root)
    return data
